spring:
  application:
    name: cache-demo
  datasource:
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
  redis:
    host: localhost
    port: 6379
server:
  port: 9101